{{- if .Values.configmaps }}
{{- $labels := .Values.labels -}}
{{- $name := .Values.name -}}
{{- range $configmapsIndex, $configmaps := .Values.configmaps }}
{{- $customLabels := $configmaps.labels -}}
{{- $annotations := $configmaps.annotations -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
{{- if eq $name $configmaps.name }}
  name: {{ $configmaps.name }}
{{- else }}
  name: {{ $name }}-{{ $configmaps.name }}
{{- end }}
  labels:
    {{- include "common.labels" $labels | nindent 4 }}
    {{- include "common.labels" $customLabels | nindent 4 }}
    {{- if $annotations }}
  annotations:
    {{- include "common.annotations" $annotations | nindent 4 }}
    {{- end }}    
data:
  {{- with $configmaps.data -}}
  {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
