{{- $labels := .Values.labels -}}
{{- range $volumeIndex, $volume := .Values.volumes }}
---
{{- $customLabels := $volume.labels }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.name }}
  labels: 
    {{- include "common.labels" $labels | nindent 4 }}
    {{- if $customLabels }}
    {{- include "common.labels" $customLabels | nindent 4 }}
    {{- end }}
spec:
  {{- if $volume.storageClassName }}
  storageClassName: {{ $volume.storageClassName }}
  {{- end }}
  {{- if $volume.volumeMode }}
  volumeMode: {{ $volume.volumeMode }}
  {{- end }}
  {{- if $volume.volumeName }}
  volumeName: {{ $volume.volumeName }}
  {{- end }}
  {{- if $volume.dataSource }}
  dataSource:
  {{ toYaml $volume.dataSource | nindent 4 }}
  {{- end }}
  accessModes:
  {{- if $volume.accessModes }}
  {{- toYaml $volume.accessModes | nindent 4 }}
  {{- else }}
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ $volume.storageSize }}
{{- end }}
