apiVersion: v2
name: common-chart
description: A general purpose helm chart for deploying components of an application
type: application
home: https://github.com/FlomasterYoda/helm-charts.git
version: 0.0.2
