name: app
####################### Image Version #######################
image:
  repository: "111111111111.dkr.ecr.us-west-2.amazonaws.com/app-repo"
  version: latest
  imagePullPolicy: IfNotPresent

####################### labels #######################
labels:
  application: "app"
  environment-type: "qa"
  team: "devops"
  domain: "shared"
  product: "shared"
  sensitive-data: "false"
  owneremail: "devops-email.com"

####################### secrets #######################
secrets: []

####################### configmap #######################
configmaps: []

####################### services #######################
services: {}

####################### serviceAccounts #######################
serviceAccounts: {}

####################### volumes #######################
volumes: {}

####################### cronJobDefaults #######################
cronJobDefaults: {}
  # image:
  #   pullPolicy: IfNotPresent
  # resources:
  #   limits:
  #     cpu: "500m"
  #     memory: 250Mi
  #   requests:
  #     cpu: "150m"
  #     memory: 150Mi
  # failedJobsHistoryLimit: 5
  # successfulJobsHistoryLimit: 5
  # concurrencyPolicy: Forbid
  # suspend: false
  # restartPolicy: OnFailure
  # envVarValuesFrom:
  #   - name: NODE_IP
  #     valueFrom:
  #       fieldRef:
  #         fieldPath: status.hostIP

####################### jobs #######################
jobs: []

####################### DeploymentDefaults #######################
deploymentDefaults: {}
  # replicas: 1
  # revisionHistoryLimit: 3
  # strategy: 
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  # dnsPolicy: ClusterFirst
  # restartPolicy: Always
  # terminationGracePeriodSeconds: 10
  # schedulerName: default-scheduler
  # nodeSelector:
  #   node-role.kubernetes.io: nodes  
  # containers:
  #   resources: 
  #     limits:
  #       cpu: 500m
  #       memory: 512Mi
  #     requests:
  #       cpu: 250m
  #       memory: 256Mi
  #   envVarValuesFrom:
  #     - name: NODE_IP
  #       valueFrom:
  #         fieldRef:
  #           fieldPath: status.hostIP

####################### Deployments #######################
deployments: {}
